### ISSUE TITLE
warnings in about screen

### ISSUE THREAD

**Issue by blakjakau** [Wrongtown/ArkSE-KeyBuddi#14]
Hey mate,

When you open the about screen for the first time (per launch) there's a bunch of warnings come up before you can view said screen.

**Comment by Wrongtown** [comment]
**_Interesting!_** 

~~Could you copy the content of the warnings (Ctrl+C while any native windows warning dialogue is highlighted should copy the text).~~

Never mind, looked at the code and found the issue, working on a fix now.

**Comment by Wrongtown** [comment]
New release is available at https://github.com/Wrongtown/ArkSE-QOL/releases/tag/v1.02
